@startuml "vaccine-comp-view"
!includeurl  https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

LAYOUT_LEFT_RIGHT
title Components diagram for the Vaccine Monitoring solution


Person(ManufacturerQA,Staff,"Manufacturer QA")
Person(ManufacturerMgr,Staff,"Manufacturer Mgr")
Person(ReeferOperator,Staff,"Reefer Operator")
System_Ext(reefer,"Refrigerator Container IoT")
System_Boundary(vms,"Vaccine_Monitoring_Solution") {
    Container(app, "Manufacturing Tracking Portal", "Javascript, Angular", "Allows customers to enter shipping order")
  
    ContainerDb(vaccineDB,"Vaccine DB","DB2","Persist Vaccine data and states")
  
    Container(reefers_mgr,"Reefer Mgr","Java, Springboot","Microservice to manage reefer container entities")
    ContainerDb(reeferDB,"Reefer DB","DB2","Persist Reefer Containers data and states")
  
    Container(message_bus, "Message Bus", "Kafka", "Transport for business events")

    Container(cold_chain_monitoring,"Cold Chain Monitoring","Agent, Kafka Stream","Process Telemetries in real time")
    Container(blockchain,"Blockchain","Blockchain API","Blockchain")
   
    Container(maintenance_process,"Maintenance Process","BPM","Business process to track reefer container maintenance")
    Container(watson_ml,"Anomaly detection scoring","Watson ML","Anomaly detection scoring")
    Container(vaccine_mgr,"Vaccine Mgr","Java,Quarkus","Microservice managing Vaccine entities")
    Container(openscale,"Watson OpenScale","Watson OpenScale","Model drift monitoring")
    Container(dashboard,"Dashboard","Watson Dashboard","Bias monitoring")

}
Rel(ManufacturerQA,app,"Triggers QA validation","HTTPS")
Rel(ManufacturerMgr,app,"Mamages vaccine process","HTTPS")
Rel(ReeferOperator,maintenance_process,"Process refrigerator maintenance","HTTPS")
Rel(app,reefers_mgr,"Uses", "HTTPS")
Rel(app,vaccine_mgr,"Uses", "HTTPS")
Rel(vaccine_mgr,vaccineDB,"Persists Vaccine data","JDBC")
Rel(reefers_mgr,reeferDB,"Persists reefers to","JDBC")

Rel(message_bus, vaccine_mgr, "Subscribes to raw material events","HTTPS,Kafka")
Rel(vaccine_mgr,message_bus, "Publishes vaccine lot events","HTTPS,Kafka")
Rel(message_bus, reefers_mgr, "Subscribes to vaccine events","HTTPS,Kafka")
Rel(message_bus,cold_chain_monitoring,"Subscribes telemetries","HTTPS,Kafka")
Rel(cold_chain_monitoring,reefers_mgr,"Notifies","Events")
Rel(cold_chain_monitoring,watson_ml,"Delegates","HTTPS")
Rel(cold_chain_monitoring,blockchain,"Delegates","HTTPS")
Rel(reefers_mgr,maintenance_process,"Triggers","HTTPS")
Rel(reefer, message_bus,"Sends telemetries","HTTPS,Kafka")
Rel(openscale,watson_ml,"Monitors drift","HTTPS")
Rel(dashboard,openscale,"Monitors drift","HTTPS")

@enduml